# Generated by Django 4.1.3 on 2022-11-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aplicacao", "0002_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
